// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Cart struct {
	ID      string    `json:"id"`
	Catalog []Product `json:"catalog"`
}

type Product struct {
	ID        string `json:"id"`
	Available bool   `json:"available"`
	Price     string `json:"price"`
	Count     int    `json:"count"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Cart  []Cart `json:"cart"`
}
